/**
 * Official Administrative Districts & Cities for Indian States
 * Reference dataset aligned with Ministry of Panchayati Raj / Local Government Directory (LGD).
 * Provides base administrative districts for each state with accurate centroid coordinates.
 */

import type { LiveCityItem } from './geocodingService'

export const STATE_OFFICIAL_DISTRICTS: Record<string, LiveCityItem[]> = {
  // Jammu and Kashmir — All 20 Official Districts
  JK: [
    {
      code: 'SGR',
      name: 'Srinagar',
      district: 'Srinagar',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 34.0837, lng: 74.7973 },
    },
    {
      code: 'IXJ',
      name: 'Jammu',
      district: 'Jammu',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 32.7266, lng: 74.857 },
    },
    {
      code: 'ANT',
      name: 'Anantnag',
      district: 'Anantnag',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.7311, lng: 75.1522 },
    },
    {
      code: 'BRM',
      name: 'Baramulla',
      district: 'Baramulla',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 34.209, lng: 74.3436 },
    },
    {
      code: 'BDG',
      name: 'Budgam',
      district: 'Budgam',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 34.015, lng: 74.72 },
    },
    {
      code: 'BPR',
      name: 'Bandipora',
      district: 'Bandipora',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 34.4225, lng: 74.6444 },
    },
    {
      code: 'DOD',
      name: 'Doda',
      district: 'Doda',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.1451, lng: 75.5478 },
    },
    {
      code: 'GBL',
      name: 'Ganderbal',
      district: 'Ganderbal',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 34.2165, lng: 74.7722 },
    },
    {
      code: 'KTH',
      name: 'Kathua',
      district: 'Kathua',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 32.3865, lng: 75.5247 },
    },
    {
      code: 'KST',
      name: 'Kishtwar',
      district: 'Kishtwar',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.315, lng: 75.7667 },
    },
    {
      code: 'KLG',
      name: 'Kulgam',
      district: 'Kulgam',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.645, lng: 75.015 },
    },
    {
      code: 'KPW',
      name: 'Kupwara',
      district: 'Kupwara',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 34.5262, lng: 74.2546 },
    },
    {
      code: 'PCH',
      name: 'Poonch',
      district: 'Poonch',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.7667, lng: 74.1 },
    },
    {
      code: 'PLW',
      name: 'Pulwama',
      district: 'Pulwama',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.8711, lng: 74.895 },
    },
    {
      code: 'RJR',
      name: 'Rajouri',
      district: 'Rajouri',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.3719, lng: 74.309 },
    },
    {
      code: 'RMB',
      name: 'Ramban',
      district: 'Ramban',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.2422, lng: 75.2411 },
    },
    {
      code: 'RSI',
      name: 'Reasi',
      district: 'Reasi',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.0811, lng: 74.8322 },
    },
    {
      code: 'SMB',
      name: 'Samba',
      district: 'Samba',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 32.5562, lng: 75.1186 },
    },
    {
      code: 'SPN',
      name: 'Shopian',
      district: 'Shopian',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 33.72, lng: 74.83 },
    },
    {
      code: 'UDH',
      name: 'Udhampur',
      district: 'Udhampur',
      stateName: 'Jammu and Kashmir',
      stateCode: 'JK',
      center: { lat: 32.925, lng: 75.1417 },
    },
  ],

  // Karnataka
  KA: [
    {
      code: 'BLR',
      name: 'Bengaluru',
      district: 'Bengaluru Urban',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 12.9716, lng: 77.5946 },
    },
    {
      code: 'MYQ',
      name: 'Mysuru',
      district: 'Mysuru',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 12.2958, lng: 76.6394 },
    },
    {
      code: 'IXE',
      name: 'Mangaluru',
      district: 'Dakshina Kannada',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 12.9141, lng: 74.856 },
    },
    {
      code: 'HBX',
      name: 'Hubballi-Dharwad',
      district: 'Dharwad',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 15.3647, lng: 75.124 },
    },
    {
      code: 'IXG',
      name: 'Belagavi',
      district: 'Belagavi',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 15.8497, lng: 74.4977 },
    },
    {
      code: 'GBI',
      name: 'Kalaburagi',
      district: 'Kalaburagi',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 17.3297, lng: 76.8343 },
    },
    {
      code: 'VDY',
      name: 'Ballari',
      district: 'Ballari',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 15.1394, lng: 76.9214 },
    },
    {
      code: 'DVG',
      name: 'Davanagere',
      district: 'Davanagere',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 14.4644, lng: 75.9218 },
    },
    {
      code: 'SME',
      name: 'Shivamogga',
      district: 'Shivamogga',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 13.9299, lng: 75.5681 },
    },
    {
      code: 'TUM',
      name: 'Tumakuru',
      district: 'Tumakuru',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 13.3379, lng: 77.101 },
    },
    {
      code: 'UDU',
      name: 'Udupi',
      district: 'Udupi',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 13.3409, lng: 74.7421 },
    },
    {
      code: 'HAS',
      name: 'Hassan',
      district: 'Hassan',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 13.0072, lng: 76.0963 },
    },
    {
      code: 'BID',
      name: 'Bidar',
      district: 'Bidar',
      stateName: 'Karnataka',
      stateCode: 'KA',
      center: { lat: 17.9104, lng: 77.5199 },
    },
  ],

  // Maharashtra
  MH: [
    {
      code: 'BOM',
      name: 'Mumbai',
      district: 'Mumbai City',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 19.076, lng: 72.8777 },
    },
    {
      code: 'PNQ',
      name: 'Pune',
      district: 'Pune',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 18.5204, lng: 73.8567 },
    },
    {
      code: 'NAG',
      name: 'Nagpur',
      district: 'Nagpur',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 21.1458, lng: 79.0882 },
    },
    {
      code: 'ISK',
      name: 'Nashik',
      district: 'Nashik',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 19.9975, lng: 73.7898 },
    },
    {
      code: 'THA',
      name: 'Thane',
      district: 'Thane',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 19.2183, lng: 72.9781 },
    },
    {
      code: 'IXU',
      name: 'Chhatrapati Sambhajinagar',
      district: 'Aurangabad',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 19.8762, lng: 75.3433 },
    },
    {
      code: 'SSE',
      name: 'Solapur',
      district: 'Solapur',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 17.6599, lng: 75.9064 },
    },
    {
      code: 'KLH',
      name: 'Kolhapur',
      district: 'Kolhapur',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 16.705, lng: 74.2433 },
    },
    {
      code: 'AMR',
      name: 'Amravati',
      district: 'Amravati',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 20.9374, lng: 77.7796 },
    },
    {
      code: 'NVM',
      name: 'Navi Mumbai',
      district: 'Thane',
      stateName: 'Maharashtra',
      stateCode: 'MH',
      center: { lat: 19.033, lng: 73.0297 },
    },
  ],

  // Delhi
  DL: [
    {
      code: 'DEL',
      name: 'New Delhi',
      district: 'New Delhi',
      stateName: 'Delhi',
      stateCode: 'DL',
      center: { lat: 28.6139, lng: 77.209 },
    },
    {
      code: 'CDL',
      name: 'Central Delhi',
      district: 'Central Delhi',
      stateName: 'Delhi',
      stateCode: 'DL',
      center: { lat: 28.6448, lng: 77.2167 },
    },
    {
      code: 'NDL',
      name: 'North Delhi',
      district: 'North Delhi',
      stateName: 'Delhi',
      stateCode: 'DL',
      center: { lat: 28.7041, lng: 77.1025 },
    },
    {
      code: 'SDL',
      name: 'South Delhi',
      district: 'South Delhi',
      stateName: 'Delhi',
      stateCode: 'DL',
      center: { lat: 28.5355, lng: 77.199 },
    },
    {
      code: 'EDL',
      name: 'East Delhi',
      district: 'East Delhi',
      stateName: 'Delhi',
      stateCode: 'DL',
      center: { lat: 28.628, lng: 77.295 },
    },
    {
      code: 'WDL',
      name: 'West Delhi',
      district: 'West Delhi',
      stateName: 'Delhi',
      stateCode: 'DL',
      center: { lat: 28.65, lng: 77.1 },
    },
  ],

  // Tamil Nadu
  TN: [
    {
      code: 'MAA',
      name: 'Chennai',
      district: 'Chennai',
      stateName: 'Tamil Nadu',
      stateCode: 'TN',
      center: { lat: 13.0827, lng: 80.2707 },
    },
    {
      code: 'CJB',
      name: 'Coimbatore',
      district: 'Coimbatore',
      stateName: 'Tamil Nadu',
      stateCode: 'TN',
      center: { lat: 11.0168, lng: 76.9558 },
    },
    {
      code: 'IXM',
      name: 'Madurai',
      district: 'Madurai',
      stateName: 'Tamil Nadu',
      stateCode: 'TN',
      center: { lat: 9.9252, lng: 78.1198 },
    },
    {
      code: 'TRZ',
      name: 'Tiruchirappalli',
      district: 'Tiruchirappalli',
      stateName: 'Tamil Nadu',
      stateCode: 'TN',
      center: { lat: 10.7905, lng: 78.7047 },
    },
    {
      code: 'SXV',
      name: 'Salem',
      district: 'Salem',
      stateName: 'Tamil Nadu',
      stateCode: 'TN',
      center: { lat: 11.6643, lng: 78.146 },
    },
    {
      code: 'TNV',
      name: 'Tirunelveli',
      district: 'Tirunelveli',
      stateName: 'Tamil Nadu',
      stateCode: 'TN',
      center: { lat: 8.7139, lng: 77.7567 },
    },
  ],

  // Uttar Pradesh
  UP: [
    {
      code: 'LKO',
      name: 'Lucknow',
      district: 'Lucknow',
      stateName: 'Uttar Pradesh',
      stateCode: 'UP',
      center: { lat: 26.8467, lng: 80.9462 },
    },
    {
      code: 'KNU',
      name: 'Kanpur',
      district: 'Kanpur Nagar',
      stateName: 'Uttar Pradesh',
      stateCode: 'UP',
      center: { lat: 26.4499, lng: 80.3319 },
    },
    {
      code: 'VNS',
      name: 'Varanasi',
      district: 'Varanasi',
      stateName: 'Uttar Pradesh',
      stateCode: 'UP',
      center: { lat: 25.3176, lng: 82.9739 },
    },
    {
      code: 'AGR',
      name: 'Agra',
      district: 'Agra',
      stateName: 'Uttar Pradesh',
      stateCode: 'UP',
      center: { lat: 27.1767, lng: 78.0081 },
    },
    {
      code: 'NDA',
      name: 'Noida',
      district: 'Gautam Buddha Nagar',
      stateName: 'Uttar Pradesh',
      stateCode: 'UP',
      center: { lat: 28.5355, lng: 77.391 },
    },
    {
      code: 'IXD',
      name: 'Prayagraj',
      district: 'Prayagraj',
      stateName: 'Uttar Pradesh',
      stateCode: 'UP',
      center: { lat: 25.4358, lng: 81.8463 },
    },
    {
      code: 'GZB',
      name: 'Ghaziabad',
      district: 'Ghaziabad',
      stateName: 'Uttar Pradesh',
      stateCode: 'UP',
      center: { lat: 28.6692, lng: 77.4538 },
    },
    {
      code: 'MEE',
      name: 'Meerut',
      district: 'Meerut',
      stateName: 'Uttar Pradesh',
      stateCode: 'UP',
      center: { lat: 28.9845, lng: 77.7064 },
    },
  ],

  // Gujarat
  GJ: [
    {
      code: 'AMD',
      name: 'Ahmedabad',
      district: 'Ahmedabad',
      stateName: 'Gujarat',
      stateCode: 'GJ',
      center: { lat: 23.0225, lng: 72.5714 },
    },
    {
      code: 'STV',
      name: 'Surat',
      district: 'Surat',
      stateName: 'Gujarat',
      stateCode: 'GJ',
      center: { lat: 21.1702, lng: 72.8311 },
    },
    {
      code: 'BDQ',
      name: 'Vadodara',
      district: 'Vadodara',
      stateName: 'Gujarat',
      stateCode: 'GJ',
      center: { lat: 22.3072, lng: 73.1812 },
    },
    {
      code: 'RAJ',
      name: 'Rajkot',
      district: 'Rajkot',
      stateName: 'Gujarat',
      stateCode: 'GJ',
      center: { lat: 22.3039, lng: 70.8022 },
    },
    {
      code: 'GAN',
      name: 'Gandhinagar',
      district: 'Gandhinagar',
      stateName: 'Gujarat',
      stateCode: 'GJ',
      center: { lat: 23.2156, lng: 72.6369 },
    },
  ],

  // West Bengal
  WB: [
    {
      code: 'CCU',
      name: 'Kolkata',
      district: 'Kolkata',
      stateName: 'West Bengal',
      stateCode: 'WB',
      center: { lat: 22.5726, lng: 88.3639 },
    },
    {
      code: 'HWH',
      name: 'Howrah',
      district: 'Howrah',
      stateName: 'West Bengal',
      stateCode: 'WB',
      center: { lat: 22.5958, lng: 88.2636 },
    },
    {
      code: 'RDP',
      name: 'Durgapur',
      district: 'Paschim Bardhaman',
      stateName: 'West Bengal',
      stateCode: 'WB',
      center: { lat: 23.5204, lng: 87.3119 },
    },
    {
      code: 'ASN',
      name: 'Asansol',
      district: 'Paschim Bardhaman',
      stateName: 'West Bengal',
      stateCode: 'WB',
      center: { lat: 23.6739, lng: 86.9524 },
    },
    {
      code: 'IXB',
      name: 'Siliguri',
      district: 'Darjeeling',
      stateName: 'West Bengal',
      stateCode: 'WB',
      center: { lat: 26.7271, lng: 88.3953 },
    },
  ],

  // Rajasthan
  RJ: [
    {
      code: 'JAI',
      name: 'Jaipur',
      district: 'Jaipur',
      stateName: 'Rajasthan',
      stateCode: 'RJ',
      center: { lat: 26.9124, lng: 75.7873 },
    },
    {
      code: 'JDH',
      name: 'Jodhpur',
      district: 'Jodhpur',
      stateName: 'Rajasthan',
      stateCode: 'RJ',
      center: { lat: 26.2389, lng: 73.0243 },
    },
    {
      code: 'UDR',
      name: 'Udaipur',
      district: 'Udaipur',
      stateName: 'Rajasthan',
      stateCode: 'RJ',
      center: { lat: 24.5854, lng: 73.7125 },
    },
    {
      code: 'KTU',
      name: 'Kota',
      district: 'Kota',
      stateName: 'Rajasthan',
      stateCode: 'RJ',
      center: { lat: 25.2138, lng: 75.8648 },
    },
    {
      code: 'AJM',
      name: 'Ajmer',
      district: 'Ajmer',
      stateName: 'Rajasthan',
      stateCode: 'RJ',
      center: { lat: 26.4499, lng: 74.6399 },
    },
  ],

  // Telangana
  TG: [
    {
      code: 'HYD',
      name: 'Hyderabad',
      district: 'Hyderabad',
      stateName: 'Telangana',
      stateCode: 'TG',
      center: { lat: 17.385, lng: 78.4867 },
    },
    {
      code: 'WGC',
      name: 'Warangal',
      district: 'Warangal Urban',
      stateName: 'Telangana',
      stateCode: 'TG',
      center: { lat: 17.9689, lng: 79.5941 },
    },
    {
      code: 'NZB',
      name: 'Nizamabad',
      district: 'Nizamabad',
      stateName: 'Telangana',
      stateCode: 'TG',
      center: { lat: 18.6725, lng: 78.0941 },
    },
    {
      code: 'KMR',
      name: 'Karimnagar',
      district: 'Karimnagar',
      stateName: 'Telangana',
      stateCode: 'TG',
      center: { lat: 18.4386, lng: 79.1288 },
    },
  ],

  // Kerala
  KL: [
    {
      code: 'TRV',
      name: 'Thiruvananthapuram',
      district: 'Thiruvananthapuram',
      stateName: 'Kerala',
      stateCode: 'KL',
      center: { lat: 8.5241, lng: 76.9366 },
    },
    {
      code: 'COK',
      name: 'Kochi',
      district: 'Ernakulam',
      stateName: 'Kerala',
      stateCode: 'KL',
      center: { lat: 9.9312, lng: 76.2673 },
    },
    {
      code: 'CCJ',
      name: 'Kozhikode',
      district: 'Kozhikode',
      stateName: 'Kerala',
      stateCode: 'KL',
      center: { lat: 11.2588, lng: 75.7804 },
    },
    {
      code: 'TCR',
      name: 'Thrissur',
      district: 'Thrissur',
      stateName: 'Kerala',
      stateCode: 'KL',
      center: { lat: 10.5276, lng: 76.2144 },
    },
  ],

  // Punjab
  PB: [
    {
      code: 'ATQ',
      name: 'Amritsar',
      district: 'Amritsar',
      stateName: 'Punjab',
      stateCode: 'PB',
      center: { lat: 31.634, lng: 74.8723 },
    },
    {
      code: 'LUH',
      name: 'Ludhiana',
      district: 'Ludhiana',
      stateName: 'Punjab',
      stateCode: 'PB',
      center: { lat: 30.901, lng: 75.8573 },
    },
    {
      code: 'JUC',
      name: 'Jalandhar',
      district: 'Jalandhar',
      stateName: 'Punjab',
      stateCode: 'PB',
      center: { lat: 31.326, lng: 75.5762 },
    },
    {
      code: 'PTA',
      name: 'Patiala',
      district: 'Patiala',
      stateName: 'Punjab',
      stateCode: 'PB',
      center: { lat: 30.3398, lng: 76.3869 },
    },
  ],

  // Haryana
  HR: [
    {
      code: 'GGN',
      name: 'Gurugram',
      district: 'Gurugram',
      stateName: 'Haryana',
      stateCode: 'HR',
      center: { lat: 28.4595, lng: 77.0266 },
    },
    {
      code: 'FBD',
      name: 'Faridabad',
      district: 'Faridabad',
      stateName: 'Haryana',
      stateCode: 'HR',
      center: { lat: 28.4089, lng: 77.3178 },
    },
    {
      code: 'PAN',
      name: 'Panipat',
      district: 'Panipat',
      stateName: 'Haryana',
      stateCode: 'HR',
      center: { lat: 29.3909, lng: 76.9635 },
    },
    {
      code: 'AMB',
      name: 'Ambala',
      district: 'Ambala',
      stateName: 'Haryana',
      stateCode: 'HR',
      center: { lat: 30.3782, lng: 76.7767 },
    },
  ],

  // Bihar
  BR: [
    {
      code: 'PAT',
      name: 'Patna',
      district: 'Patna',
      stateName: 'Bihar',
      stateCode: 'BR',
      center: { lat: 25.5941, lng: 85.1376 },
    },
    {
      code: 'GAY',
      name: 'Gaya',
      district: 'Gaya',
      stateName: 'Bihar',
      stateCode: 'BR',
      center: { lat: 24.7914, lng: 85.0002 },
    },
    {
      code: 'BGP',
      name: 'Bhagalpur',
      district: 'Bhagalpur',
      stateName: 'Bihar',
      stateCode: 'BR',
      center: { lat: 25.2425, lng: 86.9842 },
    },
    {
      code: 'MZU',
      name: 'Muzaffarpur',
      district: 'Muzaffarpur',
      stateName: 'Bihar',
      stateCode: 'BR',
      center: { lat: 26.1209, lng: 85.3647 },
    },
  ],

  // Madhya Pradesh
  MP: [
    {
      code: 'BHO',
      name: 'Bhopal',
      district: 'Bhopal',
      stateName: 'Madhya Pradesh',
      stateCode: 'MP',
      center: { lat: 23.2599, lng: 77.4126 },
    },
    {
      code: 'IDR',
      name: 'Indore',
      district: 'Indore',
      stateName: 'Madhya Pradesh',
      stateCode: 'MP',
      center: { lat: 22.7196, lng: 75.8577 },
    },
    {
      code: 'GWL',
      name: 'Gwalior',
      district: 'Gwalior',
      stateName: 'Madhya Pradesh',
      stateCode: 'MP',
      center: { lat: 26.2183, lng: 78.1828 },
    },
    {
      code: 'JLR',
      name: 'Jabalpur',
      district: 'Jabalpur',
      stateName: 'Madhya Pradesh',
      stateCode: 'MP',
      center: { lat: 23.1815, lng: 79.9864 },
    },
  ],

  // Andhra Pradesh
  AP: [
    {
      code: 'VTZ',
      name: 'Visakhapatnam',
      district: 'Visakhapatnam',
      stateName: 'Andhra Pradesh',
      stateCode: 'AP',
      center: { lat: 17.6868, lng: 83.2185 },
    },
    {
      code: 'VGA',
      name: 'Vijayawada',
      district: 'NTR',
      stateName: 'Andhra Pradesh',
      stateCode: 'AP',
      center: { lat: 16.5062, lng: 80.648 },
    },
    {
      code: 'GNT',
      name: 'Guntur',
      district: 'Guntur',
      stateName: 'Andhra Pradesh',
      stateCode: 'AP',
      center: { lat: 16.3067, lng: 80.4365 },
    },
  ],

  // Odisha
  OD: [
    {
      code: 'BBI',
      name: 'Bhubaneswar',
      district: 'Khurda',
      stateName: 'Odisha',
      stateCode: 'OD',
      center: { lat: 20.2961, lng: 85.8245 },
    },
    {
      code: 'CTC',
      name: 'Cuttack',
      district: 'Cuttack',
      stateName: 'Odisha',
      stateCode: 'OD',
      center: { lat: 20.4625, lng: 85.883 },
    },
    {
      code: 'RRK',
      name: 'Rourkela',
      district: 'Sundargarh',
      stateName: 'Odisha',
      stateCode: 'OD',
      center: { lat: 22.2604, lng: 84.8536 },
    },
  ],

  // Assam
  AS: [
    {
      code: 'GAU',
      name: 'Guwahati',
      district: 'Kamrup Metropolitan',
      stateName: 'Assam',
      stateCode: 'AS',
      center: { lat: 26.1445, lng: 91.7362 },
    },
    {
      code: 'IXS',
      name: 'Silchar',
      district: 'Cachar',
      stateName: 'Assam',
      stateCode: 'AS',
      center: { lat: 24.8333, lng: 92.7789 },
    },
  ],

  // Goa
  GA: [
    {
      code: 'GOI',
      name: 'Panaji',
      district: 'North Goa',
      stateName: 'Goa',
      stateCode: 'GA',
      center: { lat: 15.4909, lng: 73.8278 },
    },
    {
      code: 'MAO',
      name: 'Margao',
      district: 'South Goa',
      stateName: 'Goa',
      stateCode: 'GA',
      center: { lat: 15.2832, lng: 73.9862 },
    },
  ],

  // Uttarakhand
  UK: [
    {
      code: 'DED',
      name: 'Dehradun',
      district: 'Dehradun',
      stateName: 'Uttarakhand',
      stateCode: 'UK',
      center: { lat: 30.3165, lng: 78.0322 },
    },
    {
      code: 'HW',
      name: 'Haridwar',
      district: 'Haridwar',
      stateName: 'Uttarakhand',
      stateCode: 'UK',
      center: { lat: 29.9457, lng: 78.1642 },
    },
  ],

  // Himachal Pradesh
  HP: [
    {
      code: 'SLV',
      name: 'Shimla',
      district: 'Shimla',
      stateName: 'Himachal Pradesh',
      stateCode: 'HP',
      center: { lat: 31.1048, lng: 77.1734 },
    },
    {
      code: 'DHM',
      name: 'Dharamshala',
      district: 'Kangra',
      stateName: 'Himachal Pradesh',
      stateCode: 'HP',
      center: { lat: 32.219, lng: 76.3234 },
    },
  ],

  // Jharkhand
  JH: [
    {
      code: 'IXR',
      name: 'Ranchi',
      district: 'Ranchi',
      stateName: 'Jharkhand',
      stateCode: 'JH',
      center: { lat: 23.3441, lng: 85.3096 },
    },
    {
      code: 'IXW',
      name: 'Jamshedpur',
      district: 'East Singhbhum',
      stateName: 'Jharkhand',
      stateCode: 'JH',
      center: { lat: 22.8046, lng: 86.2029 },
    },
    {
      code: 'DHN',
      name: 'Dhanbad',
      district: 'Dhanbad',
      stateName: 'Jharkhand',
      stateCode: 'JH',
      center: { lat: 23.7957, lng: 86.4304 },
    },
  ],

  // Chhattisgarh
  CG: [
    {
      code: 'RPR',
      name: 'Raipur',
      district: 'Raipur',
      stateName: 'Chhattisgarh',
      stateCode: 'CG',
      center: { lat: 21.2514, lng: 81.6296 },
    },
    {
      code: 'BHL',
      name: 'Bhilai',
      district: 'Durg',
      stateName: 'Chhattisgarh',
      stateCode: 'CG',
      center: { lat: 21.2144, lng: 81.3831 },
    },
  ],

  // Chandigarh
  CH: [
    {
      code: 'IXC',
      name: 'Chandigarh',
      district: 'Chandigarh',
      stateName: 'Chandigarh',
      stateCode: 'CH',
      center: { lat: 30.7333, lng: 76.7794 },
    },
  ],

  // Ladakh
  LA: [
    {
      code: 'IXL',
      name: 'Leh',
      district: 'Leh',
      stateName: 'Ladakh',
      stateCode: 'LA',
      center: { lat: 34.1526, lng: 77.5771 },
    },
    {
      code: 'KGL',
      name: 'Kargil',
      district: 'Kargil',
      stateName: 'Ladakh',
      stateCode: 'LA',
      center: { lat: 34.5539, lng: 76.1349 },
    },
  ],

  // Puducherry
  PY: [
    {
      code: 'PNY',
      name: 'Puducherry',
      district: 'Puducherry',
      stateName: 'Puducherry',
      stateCode: 'PY',
      center: { lat: 11.9416, lng: 79.8083 },
    },
  ],
}

/**
 * Returns official administrative districts for a given state code (e.g. 'JK', 'KA')
 */
export function getOfficialDistrictsByState(stateCode: string): LiveCityItem[] {
  const normalized = (stateCode || '').toUpperCase().trim()
  return STATE_OFFICIAL_DISTRICTS[normalized] || []
}
