import React from 'react'
import type { SettlementBatch } from '../types'
import { Card, CardHeader, CardContent } from '@/shared/components/ui/Card'
import { FileText, Calendar, User, Tag } from 'lucide-react'

interface Props { batch: SettlementBatch }

export const SettlementSummaryCard: React.FC<Props> = ({ batch }) => (
  <Card className="premium-card text-left text-xs">
    <CardHeader className="pb-3 border-b border-border">
      <h3 className="font-black text-slate-800 dark:text-white text-sm flex items-center gap-2">
        <FileText className="h-4 w-4 text-primary" />
        <span>Batch Summary</span>
      </h3>
    </CardHeader>
    <CardContent className="p-4 space-y-3 font-medium">
      {[
        { icon: Tag, label: 'Batch Reference', value: batch.batchNumber },
        { icon: Calendar, label: 'Period Start', value: batch.periodStart },
        { icon: Calendar, label: 'Period End', value: batch.periodEnd },
        { icon: User, label: 'Generated By', value: batch.generatedBy },
        { icon: FileText, label: 'Total Drivers', value: `${batch.totalDrivers} drivers` },
      ].map(({ icon: Icon, label, value }) => (
        <div key={label} className="flex justify-between items-center">
          <span className="text-slate-500 flex items-center gap-1.5">
            <Icon className="h-3.5 w-3.5 text-slate-400" />
            {label}:
          </span>
          <strong className="text-slate-800 dark:text-white font-mono text-[11px]">{value}</strong>
        </div>
      ))}
      {batch.processedAt && (
        <div className="flex justify-between items-center pt-1 border-t border-border">
          <span className="text-slate-500">Processed At:</span>
          <strong className="font-mono text-[11px] text-slate-700">{new Date(batch.processedAt).toLocaleString('en-IN')}</strong>
        </div>
      )}
      {batch.completedAt && (
        <div className="flex justify-between items-center">
          <span className="text-slate-500">Completed At:</span>
          <strong className="font-mono text-[11px] text-emerald-600">{new Date(batch.completedAt).toLocaleString('en-IN')}</strong>
        </div>
      )}
    </CardContent>
  </Card>
)

export default SettlementSummaryCard
