/**
 * Centralized Endpoints Registry for API requests
 */
export const API_ENDPOINTS = {
  auth: {
    login: '/auth/admin/login',
    logout: '/auth/logout',
    me: '/auth/me',
    refreshToken: '/auth/token/refresh',
    otpSend: '/auth/admin/otp/send',
    otpVerify: '/auth/admin/otp/verify',
  },
  dashboard: {
    stats: '/dashboard/stats',
    trends: '/dashboard/trends',
    liveRides: '/dashboard/live-rides',
  },
  users: {
    list: '/admin/users',
    detail: (id: string) => `/admin/users/${id}`,
    create: '/admin/users',
    update: (id: string) => `/admin/users/${id}`,
    delete: (id: string) => `/admin/users/${id}`,
  },
  rbac: {
    permissions: '/admin/rbac/permissions',
    roles: '/admin/rbac/roles',
    rolePermissions: (slug: string) => `/admin/rbac/roles/${slug}/permissions`,
  },
  riders: {
    list: '/admin/riders',
    detail: (id: string) => `/admin/riders/${id}`,
    suspend: (id: string) => `/admin/riders/${id}/suspend`,
    block: (id: string) => `/admin/riders/${id}/block`,
    activate: (id: string) => `/admin/riders/${id}/activate`,
  },
  drivers: {
    list: '/admin/drivers',
    detail: (id: string) => `/admin/drivers/${id}`,
    suspend: (id: string) => `/admin/drivers/${id}/suspend`,
    block: (id: string) => `/admin/drivers/${id}/block`,
    activate: (id: string) => `/admin/drivers/${id}/activate`,
    verify: (id: string) => `/admin/drivers/${id}/verify`,
    documentReview: (driverId: string, documentId: string) =>
      `/admin/drivers/${driverId}/documents/${documentId}/review`,
  },
  applications: {
    list: '/admin/applications',
    create: '/admin/applications',
    detail: (id: string) => `/admin/applications/${id}`,
    approve: (id: string) => `/admin/applications/${id}/approve`,
    reject: (id: string) => `/admin/applications/${id}/reject`,
    requestResubmission: (id: string) => `/admin/applications/${id}/request-resubmission`,
    documentReview: (id: string, documentId: string) =>
      `/admin/applications/${id}/documents/${documentId}/review`,
  },
  vehicles: {
    list: '/admin/vehicles',
    detail: (id: string) => `/admin/vehicles/${id}`,
    flagRenewal: (id: string) => `/admin/vehicles/${id}/flag-renewal`,
    review: (id: string) => `/admin/vehicles/${id}/review`,
    verify: (id: string) => `/admin/vehicles/${id}/verify`,
    documentReview: (vehicleId: string, documentId: string) =>
      `/admin/vehicles/${vehicleId}/documents/${documentId}/review`,
  },
  vehicleTypes: {
    list: '/vehicle-types',
  },
  fareRules: {
    list: '/admin/fare-rules',
    detail: (id: string) => `/admin/fare-rules/${id}`,
    create: '/admin/fare-rules',
    update: (id: string) => `/admin/fare-rules/${id}`,
    activate: (id: string) => `/admin/fare-rules/${id}/activate`,
    deactivate: (id: string) => `/admin/fare-rules/${id}/deactivate`,
    delete: (id: string) => `/admin/fare-rules/${id}`,
  },
  serviceZones: {
    list: '/admin/service-zones',
  },
  surgeZones: {
    list: '/admin/surge-zones',
    detail: (id: string) => `/admin/surge-zones/${id}`,
    create: '/admin/surge-zones',
    update: (id: string) => `/admin/surge-zones/${id}`,
    delete: (id: string) => `/admin/surge-zones/${id}`,
  },
  surgeWindows: {
    list: '/admin/surge-windows',
    detail: (id: string) => `/admin/surge-windows/${id}`,
    create: '/admin/surge-windows',
    update: (id: string) => `/admin/surge-windows/${id}`,
    delete: (id: string) => `/admin/surge-windows/${id}`,
  },
  cancellationPolicies: {
    list: '/admin/cancellation-policies',
    detail: (id: string) => `/admin/cancellation-policies/${id}`,
    create: '/admin/cancellation-policies',
    update: (id: string) => `/admin/cancellation-policies/${id}`,
    activate: (id: string) => `/admin/cancellation-policies/${id}/activate`,
    deactivate: (id: string) => `/admin/cancellation-policies/${id}/deactivate`,
    delete: (id: string) => `/admin/cancellation-policies/${id}`,
  },
  invoices: {
    list: '/admin/invoices',
    detail: (id: string) => `/admin/invoices/${id}`,
  },
  invoiceTemplates: {
    list: '/admin/invoice-templates',
    create: '/admin/invoice-templates',
    update: (id: string) => `/admin/invoice-templates/${id}`,
    delete: (id: string) => `/admin/invoice-templates/${id}`,
    setDefault: (id: string) => `/admin/invoice-templates/${id}/set-default`,
  },
  promotions: {
    list: '/admin/promotions',
    detail: (id: string) => `/admin/promotions/${id}`,
    create: '/admin/promotions',
    update: (id: string) => `/admin/promotions/${id}`,
    activate: (id: string) => `/admin/promotions/${id}/activate`,
    deactivate: (id: string) => `/admin/promotions/${id}/deactivate`,
    reportOverview: '/admin/promotions/reports/overview',
    performance: (id: string) => `/admin/promotions/${id}/performance`,
  },
  campaigns: {
    list: '/admin/campaigns',
    detail: (id: string) => `/admin/campaigns/${id}`,
    create: '/admin/campaigns',
    update: (id: string) => `/admin/campaigns/${id}`,
    targets: (id: string) => `/admin/campaigns/${id}/targets`,
  },
  segments: {
    list: '/admin/segments',
    detail: (id: string) => `/admin/segments/${id}`,
    create: '/admin/segments',
    update: (id: string) => `/admin/segments/${id}`,
    delete: (id: string) => `/admin/segments/${id}`,
  },
  couponBatches: {
    list: '/admin/coupon-batches',
    detail: (id: string) => `/admin/coupon-batches/${id}`,
    create: '/admin/coupon-batches',
    generate: (id: string) => `/admin/coupon-batches/${id}/generate`,
    activate: (id: string) => `/admin/coupon-batches/${id}/activate`,
    deactivate: (id: string) => `/admin/coupon-batches/${id}/deactivate`,
  },
  coupons: {
    list: '/admin/coupons',
  },
  promoBanners: {
    list: '/admin/promo-banners',
    detail: (id: string) => `/admin/promo-banners/${id}`,
    create: '/admin/promo-banners',
    update: (id: string) => `/admin/promo-banners/${id}`,
    activate: (id: string) => `/admin/promo-banners/${id}/activate`,
    deactivate: (id: string) => `/admin/promo-banners/${id}/deactivate`,
    delete: (id: string) => `/admin/promo-banners/${id}`,
  },
  cities: {
    list: '/admin/cities',
  },
  geographic: {
    countries: '/admin/geographic/countries',
    states: '/admin/geographic/states',
    state: (id: string) => `/admin/geographic/states/${id}`,
    cities: '/admin/geographic/cities',
    city: (id: string) => `/admin/geographic/cities/${id}`,
    serviceZones: '/admin/geographic/service-zones',
    serviceZone: (id: string) => `/admin/geographic/service-zones/${id}`,
    activateServiceZone: (id: string) => `/admin/geographic/service-zones/${id}/activate`,
    deactivateServiceZone: (id: string) => `/admin/geographic/service-zones/${id}/deactivate`,
  },
  referralPrograms: {
    list: '/admin/referral-programs',
    detail: (id: string) => `/admin/referral-programs/${id}`,
    create: '/admin/referral-programs',
    update: (id: string) => `/admin/referral-programs/${id}`,
    activate: (id: string) => `/admin/referral-programs/${id}/activate`,
    deactivate: (id: string) => `/admin/referral-programs/${id}/deactivate`,
    milestones: (id: string) => `/admin/referral-programs/${id}/milestones`,
  },
  referralMilestones: {
    update: (id: string) => `/admin/referral-milestones/${id}`,
    activate: (id: string) => `/admin/referral-milestones/${id}/activate`,
    deactivate: (id: string) => `/admin/referral-milestones/${id}/deactivate`,
  },
  referralCodes: {
    list: '/admin/referral-codes',
    activate: (id: string) => `/admin/referral-codes/${id}/activate`,
    deactivate: (id: string) => `/admin/referral-codes/${id}/deactivate`,
  },
  referrals: {
    list: '/admin/referrals',
    detail: (id: string) => `/admin/referrals/${id}`,
  },
  verification: {
    list: '/verifications',
    detail: (id: string) => `/verifications/${id}`,
    approve: (id: string) => `/verifications/${id}/approve`,
    reject: (id: string) => `/verifications/${id}/reject`,
  },
  files: {
    create: '/files',
    complete: (id: string) => `/files/${id}/complete`,
    readUrl: (id: string) => `/files/${id}/url`,
  },
  monitoring: {
    health: '/admin/monitoring/health',
    performance: '/admin/monitoring/performance',
    errors: '/admin/monitoring/errors',
    alerts: '/admin/monitoring/alerts',
    ackAlert: (id: string) => `/admin/monitoring/alerts/${id}/ack`,
  },
  security: {
    sessions: '/admin/security/sessions',
    revokeSession: (id: string) => `/admin/security/sessions/${id}/revoke`,
    forceLogoutAll: '/admin/security/force-logout-all',
    loginHistory: '/admin/security/login-history',
    events: '/admin/security/events',
    policy: '/admin/security/policy',
  },
  jobs: {
    queues: '/admin/jobs/queues',
    queueJobs: (name: string) => `/admin/jobs/queues/${name}/jobs`,
    schedulers: '/admin/jobs/schedulers',
    jobDetail: (queue: string, jobId: string) => `/admin/jobs/${queue}/${jobId}`,
    mutateJob: (queue: string, jobId: string) => `/admin/jobs/${queue}/${jobId}`,
  },
  audit: {
    logs: '/admin/audit/logs',
  },
  settings: {
    general: '/admin/settings/general',
    ride: '/admin/settings/ride',
    otp: '/admin/settings/otp',
    onboarding: '/admin/settings/onboarding',
    featureFlags: '/admin/settings/feature-flags',
    maintenance: '/admin/settings/maintenance',
    maps: '/admin/settings/maps',
    mapsClientConfig: '/admin/settings/maps/client-config',
    mapsTest: '/admin/settings/maps/test',
    integrations: {
      payment: '/admin/settings/integrations/payment',
      sms: '/admin/settings/integrations/sms',
      push: '/admin/settings/integrations/push',
      email: '/admin/settings/integrations/email',
      status: '/admin/settings/integrations/status',
      paymentTest: '/admin/settings/integrations/payment/test',
      smsTest: '/admin/settings/integrations/sms/test',
      pushTest: '/admin/settings/integrations/push/test',
      emailTest: '/admin/settings/integrations/email/test',
    },
  },
  communications: {
    templates: '/admin/communications/templates',
    template: (id: string) => `/admin/communications/templates/${id}`,
    history: '/admin/communications/history',
    pushSend: '/admin/communications/push/send',
    pushSchedule: '/admin/communications/push/schedule',
    pushHistory: '/admin/communications/push/history',
    pushRetry: (id: string) => `/admin/communications/push/${id}/retry`,
  },
  operations: {
    rides: '/admin/operations/rides',
    rideDetail: (id: string) => `/admin/operations/rides/${id}`,
    rideTimeline: (id: string) => `/admin/operations/rides/${id}/timeline`,
    rideFareBreakdown: (id: string) => `/admin/operations/rides/${id}/fare-breakdown`,
    ridePayments: (id: string) => `/admin/operations/rides/${id}/payments`,
    rideDriverLocation: (id: string) => `/admin/operations/rides/${id}/driver-location`,
    rideRoute: (id: string) => `/admin/operations/rides/${id}/route`,
    rideExport: '/admin/operations/rides/export',
    liveSummary: '/admin/operations/live/summary',
    liveActiveRides: '/admin/operations/live/active-rides',
    liveMap: '/admin/operations/live/map',
    liveDrivers: '/admin/operations/live/drivers',
    liveAlerts: '/admin/operations/live/alerts',
    dispatchRequests: '/admin/operations/dispatch/requests',
    dispatchRequestDetail: (id: string) => `/admin/operations/dispatch/requests/${id}`,
    dispatchCandidates: (id: string) => `/admin/operations/dispatch/requests/${id}/candidates`,
    tickets: '/admin/operations/tickets',
    ticketDetail: (id: string) => `/admin/operations/tickets/${id}`,
    ticketCategories: '/admin/operations/tickets/categories',
    ticketAgents: '/admin/operations/tickets/agents',
    ticketAssign: (id: string) => `/admin/operations/tickets/${id}/assign`,
    ticketStatus: (id: string) => `/admin/operations/tickets/${id}/status`,
    ticketMessages: (id: string) => `/admin/operations/tickets/${id}/messages`,
    ticketResolve: (id: string) => `/admin/operations/tickets/${id}/resolve`,
    incidents: '/admin/operations/incidents',
    incidentDetail: (id: string) => `/admin/operations/incidents/${id}`,
    incidentAcknowledge: (id: string) => `/admin/operations/incidents/${id}/acknowledge`,
    incidentResolve: (id: string) => `/admin/operations/incidents/${id}/resolve`,
    incidentEscalate: (id: string) => `/admin/operations/incidents/${id}/escalate`,
    incidentNotes: (id: string) => `/admin/operations/incidents/${id}/notes`,
    incidentEvidence: (id: string) => `/admin/operations/incidents/${id}/evidence`,
    rideCancel: (id: string) => `/admin/operations/rides/${id}/actions/cancel`,
    rideNotes: (id: string) => `/admin/operations/rides/${id}/notes`,
    rideAudit: (id: string) => `/admin/operations/rides/${id}/audit`,
  },
  finance: {
    dashboard: '/admin/finance/dashboard',
    transactions: '/admin/finance/transactions',
    transaction: (id: string) => `/admin/finance/transactions/${id}`,
    reconcile: (id: string) => `/admin/finance/transactions/${id}/reconcile`,
    refunds: '/admin/finance/refunds',
    refund: (id: string) => `/admin/finance/refunds/${id}`,
    refundStartReview: (id: string) => `/admin/finance/refunds/${id}/start-review`,
    refundApprove: (id: string) => `/admin/finance/refunds/${id}/approve`,
    refundReject: (id: string) => `/admin/finance/refunds/${id}/reject`,
    refundMarkProcessing: (id: string) => `/admin/finance/refunds/${id}/mark-processing`,
    refundMarkCompleted: (id: string) => `/admin/finance/refunds/${id}/mark-completed`,
    settlements: '/admin/finance/settlements',
    settlement: (id: string) => `/admin/finance/settlements/${id}`,
    settlementDrivers: (id: string) => `/admin/finance/settlements/${id}/drivers`,
    settlementGenerate: '/admin/finance/settlements/generate',
    settlementStatus: (id: string) => `/admin/finance/settlements/${id}/status`,
    driverSearch: '/admin/finance/drivers/search',
    driverLedger: (id: string) => `/admin/finance/drivers/${id}/ledger`,
    driverBreakdown: (id: string) => `/admin/finance/drivers/${id}/breakdown`,
    disputes: '/admin/finance/disputes',
    dispute: (id: string) => `/admin/finance/disputes/${id}`,
    disputeAssign: (id: string) => `/admin/finance/disputes/${id}/assign`,
    disputeStatus: (id: string) => `/admin/finance/disputes/${id}/status`,
    disputeResolve: (id: string) => `/admin/finance/disputes/${id}/resolve`,
    disputeClose: (id: string) => `/admin/finance/disputes/${id}/close`,
    auditLogs: '/admin/finance/audit-logs',
  },
  // Shared map services, served by the configured provider (not admin-scoped).
  maps: {
    geocode: '/maps/geocode',
    route: '/maps/routes',
  },
  documents: {
    compliance: '/admin/documents/compliance',
    complianceDetail: (driverId: string) => `/admin/documents/compliance/${driverId}`,
    settings: '/admin/documents/settings',
    review: (documentId: string) => `/admin/documents/${documentId}/review`,
  },
} as const

export type ApiEndpoints = typeof API_ENDPOINTS;
